on:
  schedule:
  - cron: "0 5 * * *"
jobs:
  start_appveyor_build:
    name: Start AppVeyor Build
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Invoke AppVeyor API
        shell: pwsh
        run: |
           $apiUri = "${{ secrets.APPVEYOR_API_URI }}/builds"
           $apiToken = "${{ secrets.APPVEYOR_API_TOKEN }}"
           $headers = @{"Authorization" = "BEARER $apiToken"}
           $body = @{ accountName = "${{ secrets.APPVEYOR_ACCOUNT_NAME }}"; projectSlug = "${{ secrets.APPVEYOR_PROJECT_SLUG }}"; branch = "master" }
           $bodyJson = $body | ConvertTo-Json
           Invoke-RestMethod -Uri $apiUri -Method Post -Headers $headers -Body $bodyJson -ContentType "application/json"
      
  
